export const MIN_PLAYERS = 2;
export const MAX_PLAYERS = 6;
export const DISCONNECT_GRACE_MS = 2 * 60 * 1000;
export const SCREW_UNLOCK_SECONDS = 0;           // فتح سكرو فوري من أول الجيم
export const SCREW_UNLOCK_MS = 0;
export const START_WITH_HOST = true;
export const ALLOW_MATCH_DISCARD = true;
export const WRONG_MATCH_PENALTY_POINTS = 0;     // إلغاء عقوبة النقاط
export const WRONG_MATCH_PENALTY_MODE: 'points' | 'card' = 'points';
export const INITIAL_PEEK_COUNT = 2;
export const TURN_TRANSITION_DELAY_MS = 3000;
export const TURN_TIMEOUT_MS = 999_999_999;      // لا وقت للدور — إنفينيتي
export const BOT_THINK_TIME_MIN_MS = 1500;
export const BOT_THINK_TIME_MAX_MS = 2500;
export const ILLEGAL_WARNING_LIMIT = 999;        // تعطيل التحذيرات فعلياً
export const ILLEGAL_ATTEMPT_PENALTY_POINTS = 0; // لا عقوبة
export const TIMEOUT_PENALTY_POINTS = 0;         // لا عقوبة على التأخير
